
services:
  backend:
    build: ./backend/
    command: uvicorn app:app --host 0.0.0.0 --port 5002
    ports:
      - 5002:5002

    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: "npm run dev"

    depends_on:
      - db
      - backend

  db:
    container_name: "hosst_db"
    restart: unless-stopped
    image: postgres:13
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

    ports:
      - 5455:5455

    command: -p 5455
